/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendaDao;
import dao.MedicoDao;
import dao.PacienteDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Agenda;
import table.AgendaTabModel;
import table.MedicoTabModel;
import table.PacienteTabModel;

/**
 *
 * @author Paulo
 */
public class AgendaView extends javax.swing.JFrame {

    Agenda agenda = new Agenda();
    AgendaDao agDao = new AgendaDao();
    PacienteDao pdao = new PacienteDao();

    public AgendaView() {
        initComponents();
        URL url = this.getClass().getResource("/imagens/iconeSistema.jpg");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        txtNumeroAgendamento.setEditable(false);
        txtNumeroAgendamento.setVisible(false);
        txt_Agenda_Paciente.setEnabled(false);
        txt_Agenda_Especialidade.setEnabled(false);
        txt_Agenda_Profissional.setEnabled(false);
        txt_Rg_agenda.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_tabelas = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Paciente = new javax.swing.JTable();
        txt_Agenda_Pesquisa_paciente = new javax.swing.JTextField();
        frame_Medico = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMedico = new javax.swing.JTable();
        txt_Agenda_Pesquisa_Medico = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAgendarConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Agenda_Paciente = new javax.swing.JTextField();
        txt_Agenda_Especialidade = new javax.swing.JTextField();
        txt_Agenda_Profissional = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Rg_agenda = new javax.swing.JTextField();
        btnCancelarAgendamento = new javax.swing.JButton();
        txtNumeroAgendamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Agendamento = new javax.swing.JTable();
        cbHorario = new javax.swing.JComboBox<>();
        calendario = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento de Consultas e Exames");
        setResizable(false);
        getContentPane().setLayout(null);

        frame_tabelas.setClosable(true);
        frame_tabelas.setTitle("Lista de Pacientes");
        frame_tabelas.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacienteIcon_1.png"))); // NOI18N
        frame_tabelas.setVisible(true);

        Tabela_Paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_PacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela_Paciente);

        javax.swing.GroupLayout frame_tabelasLayout = new javax.swing.GroupLayout(frame_tabelas.getContentPane());
        frame_tabelas.getContentPane().setLayout(frame_tabelasLayout);
        frame_tabelasLayout.setHorizontalGroup(
            frame_tabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_tabelasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        frame_tabelasLayout.setVerticalGroup(
            frame_tabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_tabelasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(frame_tabelas);
        frame_tabelas.setBounds(18, 60, 470, 220);

        txt_Agenda_Pesquisa_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_Pesquisa_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Agenda_Pesquisa_paciente);
        txt_Agenda_Pesquisa_paciente.setBounds(130, 30, 162, 24);

        frame_Medico.setClosable(true);
        frame_Medico.setTitle("Lista de Médicos");
        frame_Medico.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMedico.png"))); // NOI18N
        frame_Medico.setVisible(true);

        tbMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMedico);

        javax.swing.GroupLayout frame_MedicoLayout = new javax.swing.GroupLayout(frame_Medico.getContentPane());
        frame_Medico.getContentPane().setLayout(frame_MedicoLayout);
        frame_MedicoLayout.setHorizontalGroup(
            frame_MedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_MedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        frame_MedicoLayout.setVerticalGroup(
            frame_MedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_MedicoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(frame_Medico);
        frame_Medico.setBounds(500, 60, 526, 220);

        txt_Agenda_Pesquisa_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_Pesquisa_MedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Agenda_Pesquisa_Medico);
        txt_Agenda_Pesquisa_Medico.setBounds(630, 30, 162, 24);

        jInternalFrame1.setTitle("Agenda Médica");
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(800, 420));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel6.setText("Horário:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 170, 45, 16);

        btnAgendarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AddAgenda.png"))); // NOI18N
        btnAgendarConsulta.setToolTipText("Confirmar Agendamento");
        btnAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarConsultaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendarConsulta);
        btnAgendarConsulta.setBounds(220, 130, 53, 56);

        jLabel2.setText("Paciente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 10, 53, 16);

        jLabel3.setText("Especialidade:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 82, 16);

        jLabel4.setText("Profissional:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 71, 16);

        txt_Agenda_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_PacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Agenda_Paciente);
        txt_Agenda_Paciente.setBounds(65, 6, 230, 24);
        jPanel1.add(txt_Agenda_Especialidade);
        txt_Agenda_Especialidade.setBounds(100, 100, 95, 24);
        jPanel1.add(txt_Agenda_Profissional);
        txt_Agenda_Profissional.setBounds(100, 70, 180, 24);

        jLabel8.setText("RG:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(6, 35, 30, 16);

        txt_Rg_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Rg_agendaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Rg_agenda);
        txt_Rg_agenda.setBounds(65, 31, 230, 24);

        btnCancelarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CancelarAgenda.png"))); // NOI18N
        btnCancelarAgendamento.setToolTipText("Cancelar agendamento selecionado");
        btnCancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAgendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarAgendamento);
        btnCancelarAgendamento.setBounds(280, 130, 51, 56);
        jPanel1.add(txtNumeroAgendamento);
        txtNumeroAgendamento.setBounds(440, 260, 36, 24);

        tb_Agendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_Agendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_AgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Agendamento);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(336, 6, 670, 180);

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00" }));
        jPanel1.add(cbHorario);
        cbHorario.setBounds(60, 170, 90, 26);

        calendario.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                calendarioComponentAdded(evt);
            }
        });
        calendario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                calendarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calendarioMouseEntered(evt);
            }
        });
        calendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarioPropertyChange(evt);
            }
        });
        calendario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calendarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calendarioKeyTyped(evt);
            }
        });
        calendario.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                calendarioVetoableChange(evt);
            }
        });
        jPanel1.add(calendario);
        calendario.setBounds(40, 140, 170, 29);

        jLabel5.setText("Data:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 140, 29, 16);

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 6, 990, 250);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 315, 1020, 290);

        jLabel1.setText("Buscar Médico:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 30, 110, 20);

        jLabel9.setText("Buscar Paiciente:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 30, 110, 20);

        LFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo2.png"))); // NOI18N
        getContentPane().add(LFundo);
        LFundo.setBounds(0, 0, 1050, 650);

        setSize(new java.awt.Dimension(1070, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_PacienteMouseClicked
        txt_Agenda_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(), PacienteTabModel.COL_NOME_PACIENTE).toString());
        txt_Rg_agenda.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(), PacienteTabModel.COL_RG_PACIENTE).toString());

    }//GEN-LAST:event_Tabela_PacienteMouseClicked

    private void txt_Agenda_Pesquisa_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_Pesquisa_pacienteActionPerformed
        String pesquisa = txt_Agenda_Pesquisa_paciente.getText();
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().buscarPaciente(pesquisa)));
        frame_tabelas.setVisible(true);
    }//GEN-LAST:event_txt_Agenda_Pesquisa_pacienteActionPerformed

    private void tbMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedicoMouseClicked
        txt_Agenda_Profissional.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_NOME_MEDICO).toString());
        txt_Agenda_Especialidade.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_ESPECIALIDADE).toString());

    }//GEN-LAST:event_tbMedicoMouseClicked

    private void txt_Agenda_Pesquisa_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_Pesquisa_MedicoActionPerformed
        String pesquisaMedico = txt_Agenda_Pesquisa_Medico.getText();
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().buscarMedico(pesquisaMedico)));
        frame_Medico.setVisible(true);
    }//GEN-LAST:event_txt_Agenda_Pesquisa_MedicoActionPerformed

    private void btnCancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAgendamentoActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja apagar o agendamento selecionado? ");
        if (confirmacao == 0) {
            int codigo = Integer.parseInt(txtNumeroAgendamento.getText());
            agDao.excluirAgendamento(codigo);
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        } else {
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        }
    }//GEN-LAST:event_btnCancelarAgendamentoActionPerformed

    private void txt_Rg_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Rg_agendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Rg_agendaActionPerformed

    private void txt_Agenda_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_PacienteActionPerformed

    }//GEN-LAST:event_txt_Agenda_PacienteActionPerformed

    private void btnAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarConsultaActionPerformed
        agenda.setPaciente_nome(txt_Agenda_Paciente.getText());
        agenda.setDocPaciente(txt_Rg_agenda.getText());
        agenda.setProfissional(txt_Agenda_Profissional.getText());
        agenda.setEspecialidade(txt_Agenda_Especialidade.getText());
        agenda.setHorario(cbHorario.getSelectedItem().toString());
        agenda.setData_agendamento(calendario.getDate());
        agenda.setStatus("Agendado");
        
        SimpleDateFormat dtAgenda = new SimpleDateFormat("yyyy/MM/dd");
        String dtAg = dtAgenda.format(calendario.getDate());
           
        
      if(agDao.checkAgenda(agenda.getProfissional(),dtAg, agenda.getHorario())){
          JOptionPane.showMessageDialog(null, "Já existe Agendamento para esta data e horário!");
          tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
      }else{
          agDao.agendarConsulta(agenda);
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
      }

        //Date data = (Date) calendario.getDate();
//        agDao.agendarConsulta(agenda);
//            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
            
        
////                //.getSelectedItem().toString()+cbMes.getSelectedItem()+
//                //cbAno.getSelectedItem()), cbHorario.getSelectedItem().toString())) {
//            JOptionPane.showMessageDialog(null, "Já existe Agendamento para esta data e horário!");
//           
//        } else {
//            agDao.agendarConsulta(agenda);
//            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        //}


    }//GEN-LAST:event_btnAgendarConsultaActionPerformed

    private void tb_AgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_AgendamentoMouseClicked
        txtNumeroAgendamento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_ID_AGENDAMENTO).toString());
    }//GEN-LAST:event_tb_AgendamentoMouseClicked

    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
        
    }//GEN-LAST:event_calendarioMouseClicked

    private void calendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarioPropertyChange

    }//GEN-LAST:event_calendarioPropertyChange

    private void calendarioVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_calendarioVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioVetoableChange

    private void calendarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioKeyPressed

    private void calendarioComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_calendarioComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarioComponentAdded

    private void calendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseEntered
        
    }//GEN-LAST:event_calendarioMouseEntered

    private void calendarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarioKeyTyped
  
    }//GEN-LAST:event_calendarioKeyTyped

    private void calendarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_calendarioAncestorAdded
   
    }//GEN-LAST:event_calendarioAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LFundo;
    private javax.swing.JTable Tabela_Paciente;
    private javax.swing.JButton btnAgendarConsulta;
    private javax.swing.JButton btnCancelarAgendamento;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JInternalFrame frame_Medico;
    private javax.swing.JInternalFrame frame_tabelas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbMedico;
    private javax.swing.JTable tb_Agendamento;
    private javax.swing.JTextField txtNumeroAgendamento;
    private javax.swing.JTextField txt_Agenda_Especialidade;
    private javax.swing.JTextField txt_Agenda_Paciente;
    private javax.swing.JTextField txt_Agenda_Pesquisa_Medico;
    private javax.swing.JTextField txt_Agenda_Pesquisa_paciente;
    private javax.swing.JTextField txt_Agenda_Profissional;
    private javax.swing.JTextField txt_Rg_agenda;
    // End of variables declaration//GEN-END:variables
}
