/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AgendaDao;
import dao.MedicoDao;
import dao.PacienteDao;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Agenda;
import table.AgendaTabModel;
import table.MedicoTabModel;
import table.PacienteTabModel;

/**
 *
 * @author Paulo
 */
public class AgendaView extends javax.swing.JFrame {

    Agenda agenda = new Agenda();
    AgendaDao agDao = new AgendaDao();
    PacienteDao pdao = new PacienteDao();

    public AgendaView() {
        initComponents();
        tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        txtNumeroAgendamento.setEditable(false);
        txtNumeroAgendamento.setVisible(false);
        txt_Agenda_Paciente.setEnabled(false);
        txt_Agenda_Especialidade.setEnabled(false);
        txt_Agenda_Profissional.setEnabled(false);
        txt_Rg_agenda.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_tabelas = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Paciente = new javax.swing.JTable();
        txt_Agenda_Pesquisa_paciente = new javax.swing.JTextField();
        frame_Medico = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMedico = new javax.swing.JTable();
        txt_Agenda_Pesquisa_Medico = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAgendarConsulta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_Agenda_Status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Agenda_Paciente = new javax.swing.JTextField();
        txt_Agenda_Especialidade = new javax.swing.JTextField();
        txt_Agenda_Profissional = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Rg_agenda = new javax.swing.JTextField();
        btnCancelarAgendamento = new javax.swing.JButton();
        txtNumeroAgendamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Agendamento = new javax.swing.JTable();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAno = new javax.swing.JComboBox<>();
        cbHorario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamento de Consultas e Exames");
        setResizable(false);
        getContentPane().setLayout(null);

        frame_tabelas.setClosable(true);
        frame_tabelas.setTitle("Lista de Pacientes");
        frame_tabelas.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacienteIcon_1.png"))); // NOI18N
        frame_tabelas.setVisible(true);

        Tabela_Paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_PacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela_Paciente);

        javax.swing.GroupLayout frame_tabelasLayout = new javax.swing.GroupLayout(frame_tabelas.getContentPane());
        frame_tabelas.getContentPane().setLayout(frame_tabelasLayout);
        frame_tabelasLayout.setHorizontalGroup(
            frame_tabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_tabelasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        frame_tabelasLayout.setVerticalGroup(
            frame_tabelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_tabelasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(frame_tabelas);
        frame_tabelas.setBounds(18, 60, 470, 220);

        txt_Agenda_Pesquisa_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_Pesquisa_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Agenda_Pesquisa_paciente);
        txt_Agenda_Pesquisa_paciente.setBounds(120, 30, 162, 24);

        frame_Medico.setClosable(true);
        frame_Medico.setTitle("Lista de Médicos");
        frame_Medico.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnMedico.png"))); // NOI18N
        frame_Medico.setVisible(true);

        tbMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbMedico);

        javax.swing.GroupLayout frame_MedicoLayout = new javax.swing.GroupLayout(frame_Medico.getContentPane());
        frame_Medico.getContentPane().setLayout(frame_MedicoLayout);
        frame_MedicoLayout.setHorizontalGroup(
            frame_MedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_MedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        frame_MedicoLayout.setVerticalGroup(
            frame_MedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_MedicoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(frame_Medico);
        frame_Medico.setBounds(500, 60, 526, 220);

        txt_Agenda_Pesquisa_Medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_Pesquisa_MedicoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Agenda_Pesquisa_Medico);
        txt_Agenda_Pesquisa_Medico.setBounds(640, 30, 162, 24);

        jInternalFrame1.setTitle("Agenda Médica");
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agenda.png"))); // NOI18N
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(800, 420));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel6.setText("Horário:");

        btnAgendarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AddAgenda.png"))); // NOI18N
        btnAgendarConsulta.setToolTipText("Confirmar Agendamento");
        btnAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarConsultaActionPerformed(evt);
            }
        });

        jLabel7.setText("Status:");

        jLabel2.setText("Paciente:");

        cb_Agenda_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agendado", "Atendido", "Cancelado", " " }));

        jLabel3.setText("Especialidade:");

        jLabel4.setText("Profissional:");

        jLabel5.setText("Data:");

        txt_Agenda_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Agenda_PacienteActionPerformed(evt);
            }
        });

        jLabel8.setText("RG:");

        txt_Rg_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Rg_agendaActionPerformed(evt);
            }
        });

        btnCancelarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CancelarAgenda.png"))); // NOI18N
        btnCancelarAgendamento.setToolTipText("Cancelar agendamento selecionado");
        btnCancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAgendamentoActionPerformed(evt);
            }
        });

        tb_Agendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_Agendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_AgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Agendamento);

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/", "02/", "03/", "04/", "05/", "06/", "07/", "08/", "09/", "10/", "11/", "12/", "13/", "14/", "15/", "16/", "17/", "18/", "19/", "20/", "21/", "22/", "23/", "24/", "25/", "26/", "27/", "28/", "29/", "30/", "31/", " ", " ", " " }));
        cbDia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDiaItemStateChanged(evt);
            }
        });
        cbDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDiaMouseClicked(evt);
            }
        });

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/", "02/", "03/", "04/", "05/", "06/", "07/", "08/", "09/", "10/", "11/", "12/" }));
        cbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesItemStateChanged(evt);
            }
        });

        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023" }));
        cbAno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAnoItemStateChanged(evt);
            }
        });

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(40, 40, 40)
                                .addComponent(txt_Rg_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Agenda_Paciente)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Agenda_Profissional, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Agenda_Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgendarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Agenda_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(171, 171, 171)
                                        .addComponent(txtNumeroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Agenda_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_Rg_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgendarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCancelarAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Agenda_Profissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Agenda_Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_Agenda_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 6, 990, 250);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 315, 1020, 290);

        jLabel1.setText("Buscar Médico:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 30, 110, 20);

        jLabel9.setText("Buscar Paiciente:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 30, 110, 20);

        LFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo2.png"))); // NOI18N
        getContentPane().add(LFundo);
        LFundo.setBounds(0, 0, 1050, 650);

        setSize(new java.awt.Dimension(1070, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_PacienteMouseClicked
        txt_Agenda_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(), PacienteTabModel.COL_NOME_PACIENTE).toString());
        txt_Rg_agenda.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(), PacienteTabModel.COL_RG_PACIENTE).toString());

    }//GEN-LAST:event_Tabela_PacienteMouseClicked

    private void txt_Agenda_Pesquisa_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_Pesquisa_pacienteActionPerformed
        String pesquisa = txt_Agenda_Pesquisa_paciente.getText();
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().buscarPaciente(pesquisa)));
        frame_tabelas.setVisible(true);
    }//GEN-LAST:event_txt_Agenda_Pesquisa_pacienteActionPerformed

    private void tbMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedicoMouseClicked
        txt_Agenda_Profissional.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_NOME_MEDICO).toString());
        txt_Agenda_Especialidade.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_ESPECIALIDADE).toString());

    }//GEN-LAST:event_tbMedicoMouseClicked

    private void txt_Agenda_Pesquisa_MedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_Pesquisa_MedicoActionPerformed
        String pesquisaMedico = txt_Agenda_Pesquisa_Medico.getText();
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().buscarMedico(pesquisaMedico)));
        frame_Medico.setVisible(true);
    }//GEN-LAST:event_txt_Agenda_Pesquisa_MedicoActionPerformed

    private void btnCancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAgendamentoActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja apagar o agendamento selecionado? ");
        if (confirmacao == 0) {
            int codigo = Integer.parseInt(txtNumeroAgendamento.getText());
            agDao.excluirAgendamento(codigo);
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        } else {
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        }
    }//GEN-LAST:event_btnCancelarAgendamentoActionPerformed

    private void txt_Rg_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Rg_agendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Rg_agendaActionPerformed

    private void txt_Agenda_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Agenda_PacienteActionPerformed

    }//GEN-LAST:event_txt_Agenda_PacienteActionPerformed

    private void btnAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarConsultaActionPerformed
        agenda.setPaciente_nome(txt_Agenda_Paciente.getText());
        agenda.setDocPaciente(txt_Rg_agenda.getText());
        agenda.setProfissional(txt_Agenda_Profissional.getText());
        agenda.setEspecialidade(txt_Agenda_Especialidade.getText());
        agenda.setHorario(cbHorario.getSelectedItem().toString());
        agenda.setData_agendamento(cbDia.getSelectedItem().toString()+cbMes.getSelectedItem()+cbAno.getSelectedItem());
        //agenda.setHorario(txt_Agenda_Horario.getText());
        agenda.setStatus((String) cb_Agenda_Status.getSelectedItem());
        /*if(txt_Agenda_Data.getText()==null||txt_Agenda_Data.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"ERRO:");
        }*/
        if (agDao.verificarAgenda(txt_Agenda_Profissional.getText(), (cbDia.getSelectedItem().toString()+cbMes.getSelectedItem()+
                cbAno.getSelectedItem()), cbHorario.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(null, "Já existe Agendamento para esta data e horário!");
           
        } else {
            agDao.agendarConsulta(agenda);
            tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        }


    }//GEN-LAST:event_btnAgendarConsultaActionPerformed

    private void tb_AgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_AgendamentoMouseClicked
        txtNumeroAgendamento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_ID_AGENDAMENTO).toString());
    }//GEN-LAST:event_tb_AgendamentoMouseClicked

    private void cbDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDiaMouseClicked
    
    }//GEN-LAST:event_cbDiaMouseClicked

    private void cbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesItemStateChanged
    //txt_Agenda_Data.setText(cbDia.getSelectedItem().toString()+cbMes.getSelectedItem().toString()+cbAno.getSelectedItem().toString());
    }//GEN-LAST:event_cbMesItemStateChanged

    private void cbDiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDiaItemStateChanged
    //txt_Agenda_Data.setText(cbDia.getSelectedItem().toString()+cbMes.getSelectedItem().toString()+cbAno.getSelectedItem().toString());

    }//GEN-LAST:event_cbDiaItemStateChanged

    private void cbAnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAnoItemStateChanged
    //txt_Agenda_Data.setText(cbDia.getSelectedItem().toString()+cbMes.getSelectedItem().toString()+cbAno.getSelectedItem().toString());

    }//GEN-LAST:event_cbAnoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LFundo;
    private javax.swing.JTable Tabela_Paciente;
    private javax.swing.JButton btnAgendarConsulta;
    private javax.swing.JButton btnCancelarAgendamento;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cb_Agenda_Status;
    private javax.swing.JInternalFrame frame_Medico;
    private javax.swing.JInternalFrame frame_tabelas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbMedico;
    private javax.swing.JTable tb_Agendamento;
    private javax.swing.JTextField txtNumeroAgendamento;
    private javax.swing.JTextField txt_Agenda_Especialidade;
    private javax.swing.JTextField txt_Agenda_Paciente;
    private javax.swing.JTextField txt_Agenda_Pesquisa_Medico;
    private javax.swing.JTextField txt_Agenda_Pesquisa_paciente;
    private javax.swing.JTextField txt_Agenda_Profissional;
    private javax.swing.JTextField txt_Rg_agenda;
    // End of variables declaration//GEN-END:variables
}
