/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.Connection;
import dao.AgendaDao;
import dao.Conexao;
import dao.ConsultaDao;
import dao.PacienteDao;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Agenda;
import model.Consulta;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import table.AgendaTabModel;
import table.PacienteTabModel;

/**
 *
 * @author Paulo
 */
public class ConsultaView extends javax.swing.JFrame {

    Consulta cs = new Consulta();
    ConsultaDao consulDao = new ConsultaDao();
    Agenda ag = new Agenda();
    AgendaDao agDao = new AgendaDao();

    public ConsultaView() {
        initComponents();
        txtDataAtendimento.setEnabled(false);
        txtDataAtendimento.setEnabled(false);
        txtRgPaciente.setEnabled(false);
        txtIdAgendamento.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPacienteAtendimento = new javax.swing.JTextField();
        txtRepousoDias = new javax.swing.JTextField();
        txtDataAtendimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTxtInfoAtestado = new javax.swing.JTextArea();
        frameTabelaAtendimento = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_Agendamento = new javax.swing.JTable();
        btnImprimirAtestado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSalvarAtestado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        cb_Agenda_Status = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtRgPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdAgendamento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Atendimento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(325, 16, 72, 16);

        jLabel2.setText("Busca Agendamentos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 128, 16);

        jLabel4.setText("Dias de repouso:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 103, 110, 16);

        jLabel6.setText("Data:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 145, 29, 16);

        txtPacienteAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteAtendimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPacienteAtendimento);
        txtPacienteAtendimento.setBounds(180, 60, 136, 24);
        getContentPane().add(txtRepousoDias);
        txtRepousoDias.setBounds(160, 100, 32, 24);
        getContentPane().add(txtDataAtendimento);
        txtDataAtendimento.setBounds(81, 141, 96, 24);

        areaTxtInfoAtestado.setColumns(20);
        areaTxtInfoAtestado.setRows(5);
        jScrollPane1.setViewportView(areaTxtInfoAtestado);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 360, 618, 100);

        frameTabelaAtendimento.setVisible(true);

        tb_Agendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_Agendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_AgendamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_Agendamento);

        javax.swing.GroupLayout frameTabelaAtendimentoLayout = new javax.swing.GroupLayout(frameTabelaAtendimento.getContentPane());
        frameTabelaAtendimento.getContentPane().setLayout(frameTabelaAtendimentoLayout);
        frameTabelaAtendimentoLayout.setHorizontalGroup(
            frameTabelaAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTabelaAtendimentoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameTabelaAtendimentoLayout.setVerticalGroup(
            frameTabelaAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTabelaAtendimentoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        getContentPane().add(frameTabelaAtendimento);
        frameTabelaAtendimento.setBounds(40, 171, 627, 127);

        btnImprimirAtestado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconBtnImprimir.png"))); // NOI18N
        btnImprimirAtestado.setToolTipText("Imprimir Atestado");
        btnImprimirAtestado.setBorder(null);
        btnImprimirAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirAtestadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimirAtestado);
        btnImprimirAtestado.setBounds(610, 470, 50, 45);

        jLabel7.setText("Informações e recomendaçoes.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 340, 204, 16);

        btnSalvarAtestado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btnSalvarAtestado.setToolTipText("Iniciar novo atendimento");
        btnSalvarAtestado.setBorder(null);
        btnSalvarAtestado.setPreferredSize(new java.awt.Dimension(70, 56));
        btnSalvarAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAtestadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarAtestado);
        btnSalvarAtestado.setBounds(540, 470, 50, 45);

        jLabel8.setText("CID:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 310, 30, 20);
        getContentPane().add(txtCid);
        txtCid.setBounds(90, 310, 86, 24);

        jLabel9.setText("Hora:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(195, 145, 40, 16);
        getContentPane().add(txtHora);
        txtHora.setBounds(241, 141, 70, 24);

        cb_Agenda_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atendido", "Ausente" }));
        getContentPane().add(cb_Agenda_Status);
        cb_Agenda_Status.setBounds(567, 55, 90, 26);

        jLabel10.setText("Status:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 60, 40, 16);
        getContentPane().add(txtRgPaciente);
        txtRgPaciente.setBounds(370, 60, 100, 24);

        jLabel3.setText("RG:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(325, 64, 30, 16);

        txtIdAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAgendamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdAgendamento);
        txtIdAgendamento.setBounds(358, 141, 33, 24);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaFundo.png"))); // NOI18N
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -4, 680, 530);

        setSize(new java.awt.Dimension(695, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPacienteAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteAtendimentoActionPerformed
        String pesquisa = txtPacienteAtendimento.getText();
        tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().buscarAgendamento(pesquisa)));
        frameTabelaAtendimento.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteAtendimentoActionPerformed

    private void btnSalvarAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAtestadoActionPerformed
        txtPacienteAtendimento.setText("");
        txtRepousoDias.setText("");
        txtCid.setText("");
        txtDataAtendimento.setText("");
        txtHora.setText("");
        txtRepousoDias.setText("");
        txtRgPaciente.setText("");
        areaTxtInfoAtestado.setText("");
        
    }//GEN-LAST:event_btnSalvarAtestadoActionPerformed

    private void tb_AgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_AgendamentoMouseClicked
        txtPacienteAtendimento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_NOME_PACIENTE).toString());
        txtDataAtendimento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_DATA_AGENDAMENTO).toString());
        txtHora.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_HORARIO).toString());
        //txtAtendimentoRG.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(),AgendaTabModel.).toString());
        txtPacienteAtendimento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_NOME_PACIENTE).toString());
        txtRgPaciente.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_RG_PACIENTE).toString());
        txtIdAgendamento.setText(tb_Agendamento.getValueAt(tb_Agendamento.getSelectedRow(), AgendaTabModel.COL_ID_AGENDAMENTO).toString());
    }//GEN-LAST:event_tb_AgendamentoMouseClicked

    private void btnImprimirAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirAtestadoActionPerformed
        //Salva atestado no banco apenas para impressão
        cs.setPacienteConsulta(txtPacienteAtendimento.getText());
        cs.setDocPaciente(txtRgPaciente.getText());
        cs.setDiasRepouso(Integer.parseInt(txtRepousoDias.getText()));
        cs.setCid(txtCid.getText());
        cs.setHoraConsulta(txtHora.getText());
        cs.setInfoAtestado(areaTxtInfoAtestado.getText());
        consulDao.salvarAtestado(cs);
        //Atualizando o Status do agendamento
        int codAgenda = Integer.parseInt(txtIdAgendamento.getText());
        ag.setId_agendamento(codAgenda);
        ag.setStatus(cb_Agenda_Status.getSelectedItem().toString());
        agDao.alterarStatus(ag);
        //Gerando arquivo em pdf com os dados informados.
        Connection conn = (Connection) new Conexao().getConexao();
        String src = "atestado.jasper";
        JasperPrint jasperPrint = null;
        
        try {
            jasperPrint = JasperFillManager.fillReport(src, null, conn);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);
        tb_Agendamento.setModel(new AgendaTabModel(new AgendaDao().listarAgendamento()));
        consulDao.gerarAtendimento();
    }//GEN-LAST:event_btnImprimirAtestadoActionPerformed

    private void txtIdAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTxtInfoAtestado;
    private javax.swing.JButton btnImprimirAtestado;
    private javax.swing.JButton btnSalvarAtestado;
    private javax.swing.JComboBox<String> cb_Agenda_Status;
    private javax.swing.JInternalFrame frameTabelaAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_Agendamento;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtDataAtendimento;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdAgendamento;
    private javax.swing.JTextField txtPacienteAtendimento;
    private javax.swing.JTextField txtRepousoDias;
    private javax.swing.JTextField txtRgPaciente;
    // End of variables declaration//GEN-END:variables
}
