package view;

import com.mysql.jdbc.Connection;
import dao.Conexao;
import dao.MedicoDao;
import model.Medico;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import table.MedicoTabModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.view.JasperViewer;

public class MedicoView extends javax.swing.JFrame {

    Medico med = new Medico();
    MedicoDao mdao = new MedicoDao();

    public MedicoView() {
        initComponents();
        setLocationRelativeTo(null);
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCRM = new javax.swing.JTextField();
        txtNomeMedico = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedico = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        cbEspecialidade = new javax.swing.JComboBox<>();
        btnRelatorioMedicos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medicos");
        getContentPane().setLayout(null);

        jLabel1.setText("CRM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 60, 40, 16);

        jLabel2.setText("Médico:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(25, 58, 44, 16);

        jLabel3.setText("Especialidade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 109, 82, 16);
        getContentPane().add(txtCRM);
        txtCRM.setBounds(450, 60, 90, 24);
        getContentPane().add(txtNomeMedico);
        txtNomeMedico.setBounds(70, 60, 280, 24);
        getContentPane().add(txtEspecialidade);
        txtEspecialidade.setBounds(122, 105, 92, 24);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar Médico");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(366, 105, 37, 28);

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar Campos.");
        btnLimpar.setBorder(null);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(409, 105, 37, 28);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagar.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir Registro");
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(495, 105, 37, 28);

        tbMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbMedico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(25, 139, 508, 112);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisa);
        txtPesquisa.setBounds(212, 341, 321, 24);

        jLabel4.setText("Pesquisar por nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(76, 345, 118, 16);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnAtualizar.setToolTipText("Atualizar Registro");
        btnAtualizar.setBorder(null);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(452, 105, 37, 28);

        cbEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clinico Geral", "Ortopedista", "Ginecologista", "Urologista", "Ofitalmologista" }));
        cbEspecialidade.setPreferredSize(new java.awt.Dimension(95, 28));
        getContentPane().add(cbEspecialidade);
        cbEspecialidade.setBounds(226, 105, 95, 20);

        btnRelatorioMedicos.setText("Imprimir");
        btnRelatorioMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorioMedicos);
        btnRelatorioMedicos.setBounds(443, 282, 90, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Cadastro de Médicos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(214, 6, 152, 19);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundomedio.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 560, 390);

        setSize(new java.awt.Dimension(580, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        med.setCrm_medico(Integer.parseInt(txtCRM.getText()));
        med.setNome_medico(txtNomeMedico.getText());
        med.setEspecialidade(txtEspecialidade.getText());
        med.setEspecialidade((String) cbEspecialidade.getSelectedItem());
        mdao.cadastrarMedico(med);
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tbMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedicoMouseClicked
        txtCRM.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_CRM_MEDICO).toString());
        txtNomeMedico.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_NOME_MEDICO).toString());
        txtEspecialidade.setText(tbMedico.getValueAt(tbMedico.getSelectedRow(), MedicoTabModel.COL_ESPECIALIDADE).toString());
        txtCRM.setEnabled(false);
        //txtCRM.setEditable(false);
    }//GEN-LAST:event_tbMedicoMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        med.setCrm_medico(Integer.parseInt(txtCRM.getText()));
        med.setNome_medico(txtNomeMedico.getText());
        med.setEspecialidade((String) cbEspecialidade.getSelectedItem());
        mdao.alterarMedico(med);
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtCRM.setText("");
        txtNomeMedico.setText("");
        txtEspecialidade.setText("");
        txtPesquisa.setText("");
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));
        txtCRM.setEnabled(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Integer apg = Integer.valueOf(JOptionPane.showConfirmDialog(null, "Deseja realmente apagar o registro atual?"));
        if (apg == 0) {
            int codigo = Integer.parseInt(txtCRM.getText());
            mdao.excluirMedico(codigo);
            tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));
        } else {
            tbMedico.setModel(new MedicoTabModel(new MedicoDao().listarTodos()));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        String pesquisa = txtPesquisa.getText();
        tbMedico.setModel(new MedicoTabModel(new MedicoDao().bucarMedico(pesquisa)));
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnRelatorioMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioMedicosActionPerformed
        Connection conn = (Connection) new Conexao().getConexao();
        String src = "report1.jasper";
        JasperPrint jasperPrint = null;

        try {
            jasperPrint = JasperFillManager.fillReport(src, null, conn);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        JasperViewer view = new JasperViewer(jasperPrint, false);
        view.setVisible(true);

    }//GEN-LAST:event_btnRelatorioMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRelatorioMedicos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEspecialidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbMedico;
    private javax.swing.JTextField txtCRM;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
