/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.PacienteDao;
import model.Paciente;
import table.PacienteTabModel;

/**
 *
 * @author Paulo
 */
public class PacienteView extends javax.swing.JFrame {
    Paciente pac = new Paciente();
    PacienteDao pacdao = new PacienteDao();
    AgendaView agv = new AgendaView();
  
    public PacienteView() {
        initComponents();
        setLocationRelativeTo(null);
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().listarPaciente()));
        //txt_Id_Paciente.setEditable(false);
        //txt_Id_Paciente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Id_Paciente = new javax.swing.JTextField();
        txt_Nome_Paciente = new javax.swing.JTextField();
        txt_Rg_Paciente = new javax.swing.JTextField();
        txt_Idade_Paciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Telefone_Paciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Paciente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Buscar_Paciente = new javax.swing.JTextField();
        btnSalvarPaciente = new javax.swing.JButton();
        btnEditarPaciente = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnApagarPaciente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Nº Prontuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 70, 78, 16);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 106, 36, 16);

        jLabel3.setText("Nº RG: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(16, 136, 37, 16);

        jLabel4.setText("Idade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(398, 106, 34, 16);

        txt_Id_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Id_Paciente);
        txt_Id_Paciente.setBounds(100, 66, 61, 24);

        txt_Nome_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nome_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nome_Paciente);
        txt_Nome_Paciente.setBounds(58, 102, 226, 24);
        getContentPane().add(txt_Rg_Paciente);
        txt_Rg_Paciente.setBounds(59, 132, 128, 24);
        getContentPane().add(txt_Idade_Paciente);
        txt_Idade_Paciente.setBounds(438, 102, 31, 24);

        jLabel5.setText("Telefone: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 166, 55, 16);

        txt_Telefone_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Telefone_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Telefone_Paciente);
        txt_Telefone_Paciente.setBounds(83, 162, 386, 24);

        Tabela_Paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela_Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_PacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Paciente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(16, 266, 453, 96);

        jLabel6.setText("Cadastro de Pacientes");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 20, 129, 16);

        jLabel7.setText("Buscar: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(16, 384, 47, 16);

        txt_Buscar_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar_PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Buscar_Paciente);
        txt_Buscar_Paciente.setBounds(75, 380, 394, 24);

        btnSalvarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarPaciente);
        btnSalvarPaciente.setBounds(173, 206, 62, 48);

        btnEditarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarPaciente);
        btnEditarPaciente.setBounds(327, 206, 62, 48);

        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimparCampos);
        btnLimparCampos.setBounds(247, 206, 62, 48);

        btnApagarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/apagar.png"))); // NOI18N
        btnApagarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagarPaciente);
        btnApagarPaciente.setBounds(407, 206, 62, 48);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelaPaciente.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, 6, 500, 440);

        setBounds(0, 0, 515, 478);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Id_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Id_PacienteActionPerformed

    private void txt_Nome_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nome_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nome_PacienteActionPerformed

    private void btnSalvarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPacienteActionPerformed
        pac.setNome(txt_Nome_Paciente.getText());
        pac.setRgPaciente(txt_Rg_Paciente.getText());
        pac.setIdade(Integer.parseInt(txt_Idade_Paciente.getText()));
        pac.setTelefone(txt_Telefone_Paciente.getText());
        pacdao.cadastrarPaciente(pac);
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().listarPaciente()));
    }//GEN-LAST:event_btnSalvarPacienteActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        txt_Buscar_Paciente.setText("");
        txt_Id_Paciente.setText("");
        txt_Nome_Paciente.setText("");
        txt_Rg_Paciente.setText("");
        txt_Idade_Paciente.setText("");
        txt_Telefone_Paciente.setText("");
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnEditarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPacienteActionPerformed
        pac.setIdPaciente(Integer.parseInt(txt_Id_Paciente.getText()));
        pac.setNome(txt_Nome_Paciente.getText());
        pac.setRgPaciente(txt_Rg_Paciente.getText());
        pac.setIdade(Integer.parseInt(txt_Idade_Paciente.getText()));
        pac.setTelefone(txt_Telefone_Paciente.getText());
        pacdao.atualizarPaciente(pac);
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().listarPaciente()));
        
        
    }//GEN-LAST:event_btnEditarPacienteActionPerformed

    private void txt_Buscar_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar_PacienteActionPerformed
        String pesquisa = txt_Buscar_Paciente.getText();
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().buscarPaciente(pesquisa)));
      
    }//GEN-LAST:event_txt_Buscar_PacienteActionPerformed

    private void Tabela_PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_PacienteMouseClicked
        //campoTexto.setText=> seta o valor no campo de text
        //Tabela.getValueAt=> pega o valor da tabela
        //  
        txt_Id_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(),PacienteTabModel.COL_ID_PACIENTE).toString());
        txt_Nome_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(),PacienteTabModel.COL_NOME_PACIENTE).toString());
        txt_Rg_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(),PacienteTabModel.COL_RG_PACIENTE).toString());
        txt_Idade_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(),PacienteTabModel.COL_IDADE_PACIENTE).toString());
        txt_Telefone_Paciente.setText(Tabela_Paciente.getValueAt(Tabela_Paciente.getSelectedRow(),PacienteTabModel.COL_TELEFONE_PACIENTE).toString());
        
    }//GEN-LAST:event_Tabela_PacienteMouseClicked

    private void btnApagarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarPacienteActionPerformed
        int codigo  =  Integer.parseInt(txt_Id_Paciente.getText());
        pacdao.excluirPaciente(codigo);
        Tabela_Paciente.setModel(new PacienteTabModel(new PacienteDao().listarPaciente()));
        
    }//GEN-LAST:event_btnApagarPacienteActionPerformed

    private void txt_Telefone_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Telefone_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Telefone_PacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_Paciente;
    private javax.swing.JButton btnApagarPaciente;
    private javax.swing.JButton btnEditarPaciente;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Buscar_Paciente;
    private javax.swing.JTextField txt_Id_Paciente;
    private javax.swing.JTextField txt_Idade_Paciente;
    private javax.swing.JTextField txt_Nome_Paciente;
    private javax.swing.JTextField txt_Rg_Paciente;
    private javax.swing.JTextField txt_Telefone_Paciente;
    // End of variables declaration//GEN-END:variables
}
